language: android
android:
  components:
    - build-tools-28.0.3
    - android-28
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.gradle/wrapper
  - $HOME/.gradle/caches/modules-2/files-2.1

before_install:
  - chmod +x gradlew

script:
  - ./gradlew desktop:dist
  - ./gradlew android:assembleRelease